export const LOCAL_STORAGE_DATA_KEY = "YACEP_EMO_DATA"
export const LOCAL_STORAGE_INFO_KEY = "YACEP_EMO_INFO"
export const LOCAL_STORAGE_GROUP_MENTION = "CHATPP_GROUP_MENTION"
export const LOCAL_STORAGE_ROOM_SHORTCUT = "CHATPP_ROOM_SHORTCUT"
export const LOCAL_STORAGE_DISABLE_NOTIFY_ROOM = "CHATPP_DISABLE_NOTIFY_ROOM"
export const CHROME_LOCAL_KEY = "CHATPP_CHROME_LOCAL_DATA"
export const CHROME_SYNC_KEY = "CHATPP_CHROME_SYNC_DATA"
export const CHROME_SYNC_GROUP_KEY = "CHATPP_CHROME_SYNC_GROUP"
export const CHROME_SYNC_ROOM_KEY = "CHATPP_CHROME_SYNC_ROOM"
export const CHROME_SYNC_DISABLE_NOTIFY_ROOM_KEY = "CHATPP_CHROME_SYNC_DISABLE_NOTIFY_ROOM"
export const DEFAULT_DATA_URL = "https://dl.dropboxusercontent.com/s/lmxis68cfh4v1ho/default.json?dl=1"
export const ADVERTISEMENT_URL = "https://dl.dropboxusercontent.com/s/jsmceot0pqi8lpk/chatppad.json?dl=1"
export const VERSION_CHROME = "VERSION_CHROME"
export const VERSION_FIREFOX = "VERSION_FIREFOX"
export const VERSION_NAME_DEV = "dev"
export const VERSION_NAME_RELEASE = "final"
export const DEFAULT_IMG_HOST = "https://chatpp.thangtd.com/"
export const DELAY_TIME = 6000
export const FORCE_TURN_OFF_THUMBNAIL = 1
export const ADVERTISEMENT_LOAD_TIMEOUT = 1000 * 60 * 30
export const TO_ALL_MARK = "TO ALL >>>"
